apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops-app
          image: ${{ secrets.DOCKER_USERNAME}}/devsecops-factory:latest
          ports:
            - containerPort: 8080